// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StudentPortalPracticeTwo.Database;

#nullable disable

namespace StudentPortalPracticeTwo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260824195729_FixedDatabaseReset")]
    partial class FixedDatabaseReset
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClassSessionUserProgramModel", b =>
                {
                    b.Property<int>("CurrentSessionsId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentProgramModelsId")
                        .HasColumnType("integer");

                    b.HasKey("CurrentSessionsId", "StudentProgramModelsId");

                    b.HasIndex("StudentProgramModelsId");

                    b.ToTable("ClassSessionUserProgramModel");
                });

            modelBuilder.Entity("ClassSessionUserProgramModel1", b =>
                {
                    b.Property<int>("RegisteredSessionsId")
                        .HasColumnType("integer");

                    b.Property<int>("RegisteredStudentProgramModelsId")
                        .HasColumnType("integer");

                    b.HasKey("RegisteredSessionsId", "RegisteredStudentProgramModelsId");

                    b.HasIndex("RegisteredStudentProgramModelsId");

                    b.ToTable("ClassSessionUserProgramModel1");
                });

            modelBuilder.Entity("CourseDegree", b =>
                {
                    b.Property<int>("CoursesId")
                        .HasColumnType("integer");

                    b.Property<int>("DegreesId")
                        .HasColumnType("integer");

                    b.HasKey("CoursesId", "DegreesId");

                    b.HasIndex("DegreesId");

                    b.ToTable("CourseDegree");
                });

            modelBuilder.Entity("CourseUserProgramModel", b =>
                {
                    b.Property<int>("CompletedCoursesId")
                        .HasColumnType("integer");

                    b.Property<int>("UserProgramModelId")
                        .HasColumnType("integer");

                    b.HasKey("CompletedCoursesId", "UserProgramModelId");

                    b.HasIndex("UserProgramModelId");

                    b.ToTable("CourseUserProgramModel");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Application.AcademicHistoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer");

                    b.Property<byte[]>("CollegeTranscript")
                        .HasColumnType("bytea");

                    b.Property<string>("CollegeTranscriptFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("HighschoolTranscript")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("HighschoolTranscriptFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId")
                        .IsUnique();

                    b.ToTable("AcademicHistoryDb");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Application.ApplicationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApprovedStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ApplicationDb");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Application.DraftAcademicHistoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("CollegeTranscript")
                        .HasColumnType("bytea");

                    b.Property<string>("CollegeTranscriptFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DraftApplicationId")
                        .HasColumnType("integer");

                    b.Property<byte[]>("HighschoolTranscript")
                        .HasColumnType("bytea");

                    b.Property<string>("HighschoolTranscriptFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DraftApplicationId")
                        .IsUnique();

                    b.ToTable("DraftAcademicHistoryDb");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Application.DraftApplicationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DraftApplicationDb");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Application.DraftEmergencyContactModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DraftApplicationId")
                        .HasColumnType("integer");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DraftApplicationId");

                    b.ToTable("DraftEmergencyContact");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Application.DraftStudentContactModel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("AltPhone")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DraftStudentContact");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Application.DraftStudentEssayModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DraftApplicationId")
                        .HasColumnType("integer");

                    b.Property<string>("ResponseOne")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponseThree")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponseTwo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DraftApplicationId")
                        .IsUnique();

                    b.ToTable("DraftEssayDb");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Application.DraftStudentInfoModel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int?>("CitizenshipCountry")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("Race")
                        .HasColumnType("integer");

                    b.Property<string>("StateOrProvince")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StreetOneAddress")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("StreetTwoAddress")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("Zipcode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("DraftStudentInfoDb");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Application.DraftStudentProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer");

                    b.Property<int?>("SelectedProgramId")
                        .HasColumnType("integer");

                    b.Property<int?>("StartTermId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId")
                        .IsUnique();

                    b.HasIndex("SelectedProgramId");

                    b.HasIndex("StartTermId");

                    b.ToTable("DraftStudentProgram");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Application.EmergencyContactModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("EmergencyContactDb");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Application.StudentContactModel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("AltPhone")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StudentContactDb");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Application.StudentEssayModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer");

                    b.Property<string>("ResponseOne")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("character varying(700)");

                    b.Property<string>("ResponseThree")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("character varying(700)");

                    b.Property<string>("ResponseTwo")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("character varying(700)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId")
                        .IsUnique();

                    b.ToTable("EssayDb");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Application.StudentInfoModel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("CitizenshipCountry")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Race")
                        .HasColumnType("integer");

                    b.Property<string>("StateOrProvince")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StreetOneAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("StreetTwoAddress")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Zipcode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("StudentInfoDb");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Application.StudentProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer");

                    b.Property<int>("SelectedProgramId")
                        .HasColumnType("integer");

                    b.Property<int>("StartTermId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId")
                        .IsUnique();

                    b.HasIndex("SelectedProgramId");

                    b.HasIndex("StartTermId");

                    b.ToTable("StudentProgramDb");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Degrees.ClassSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentCount")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("InstructorId")
                        .HasColumnType("integer");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("TermId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("InstructorId");

                    b.HasIndex("TermId");

                    b.ToTable("ClassSessionDb");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Degrees.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Credits")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("CourseDb");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Degrees.Degree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("DegreeDb");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Degrees.Term", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AvailableToRegisterClasses")
                        .HasColumnType("boolean");

                    b.Property<int>("Season")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TermDb");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Users.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Users.Faculty.PendingFaculty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HashedInviteToken")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PendingFacultyDb");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Users.Students.UserProgramModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DegreeId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DegreeId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProgram");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Users.UserContactModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserContactDb");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Users.UserEmergencyContactModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserEmergencyDb");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Users.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId");

                    b.ToTable("UserDb");

                    b.HasDiscriminator<string>("Discriminator").HasValue("UserModel");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Users.Admin.AdminModel", b =>
                {
                    b.HasBaseType("StudentPortalPracticeTwo.Database.Models.Users.UserModel");

                    b.HasDiscriminator().HasValue("AdminModel");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Users.Faculty.Faculty", b =>
                {
                    b.HasBaseType("StudentPortalPracticeTwo.Database.Models.Users.UserModel");

                    b.HasDiscriminator().HasValue("Faculty");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Users.Students.Student", b =>
                {
                    b.HasBaseType("StudentPortalPracticeTwo.Database.Models.Users.UserModel");

                    b.Property<int?>("FinalApplicationId")
                        .HasColumnType("integer");

                    b.HasIndex("FinalApplicationId");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("ClassSessionUserProgramModel", b =>
                {
                    b.HasOne("StudentPortalPracticeTwo.Database.Models.Degrees.ClassSession", null)
                        .WithMany()
                        .HasForeignKey("CurrentSessionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentPortalPracticeTwo.Database.Models.Users.Students.UserProgramModel", null)
                        .WithMany()
                        .HasForeignKey("StudentProgramModelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClassSessionUserProgramModel1", b =>
                {
                    b.HasOne("StudentPortalPracticeTwo.Database.Models.Degrees.ClassSession", null)
                        .WithMany()
                        .HasForeignKey("RegisteredSessionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentPortalPracticeTwo.Database.Models.Users.Students.UserProgramModel", null)
                        .WithMany()
                        .HasForeignKey("RegisteredStudentProgramModelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourseDegree", b =>
                {
                    b.HasOne("StudentPortalPracticeTwo.Database.Models.Degrees.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentPortalPracticeTwo.Database.Models.Degrees.Degree", null)
                        .WithMany()
                        .HasForeignKey("DegreesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourseUserProgramModel", b =>
                {
                    b.HasOne("StudentPortalPracticeTwo.Database.Models.Degrees.Course", null)
                        .WithMany()
                        .HasForeignKey("CompletedCoursesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentPortalPracticeTwo.Database.Models.Users.Students.UserProgramModel", null)
                        .WithMany()
                        .HasForeignKey("UserProgramModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("StudentPortalPracticeTwo.Database.Models.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("StudentPortalPracticeTwo.Database.Models.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentPortalPracticeTwo.Database.Models.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("StudentPortalPracticeTwo.Database.Models.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Application.AcademicHistoryModel", b =>
                {
                    b.HasOne("StudentPortalPracticeTwo.Database.Models.Application.ApplicationModel", "Application")
                        .WithOne("AcademicHistory")
                        .HasForeignKey("StudentPortalPracticeTwo.Database.Models.Application.AcademicHistoryModel", "ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Application.DraftAcademicHistoryModel", b =>
                {
                    b.HasOne("StudentPortalPracticeTwo.Database.Models.Application.DraftApplicationModel", "DraftApplication")
                        .WithOne("DraftAcademicHistory")
                        .HasForeignKey("StudentPortalPracticeTwo.Database.Models.Application.DraftAcademicHistoryModel", "DraftApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DraftApplication");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Application.DraftEmergencyContactModel", b =>
                {
                    b.HasOne("StudentPortalPracticeTwo.Database.Models.Application.DraftApplicationModel", "Application")
                        .WithMany("DraftEmergencyContact")
                        .HasForeignKey("DraftApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Application.DraftStudentContactModel", b =>
                {
                    b.HasOne("StudentPortalPracticeTwo.Database.Models.Application.DraftApplicationModel", "Application")
                        .WithOne("DraftStudentContact")
                        .HasForeignKey("StudentPortalPracticeTwo.Database.Models.Application.DraftStudentContactModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Application.DraftStudentEssayModel", b =>
                {
                    b.HasOne("StudentPortalPracticeTwo.Database.Models.Application.DraftApplicationModel", "DraftApplication")
                        .WithOne("DraftEssays")
                        .HasForeignKey("StudentPortalPracticeTwo.Database.Models.Application.DraftStudentEssayModel", "DraftApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DraftApplication");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Application.DraftStudentInfoModel", b =>
                {
                    b.HasOne("StudentPortalPracticeTwo.Database.Models.Application.DraftApplicationModel", "Application")
                        .WithOne("DraftStudentInfo")
                        .HasForeignKey("StudentPortalPracticeTwo.Database.Models.Application.DraftStudentInfoModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Application.DraftStudentProgram", b =>
                {
                    b.HasOne("StudentPortalPracticeTwo.Database.Models.Application.DraftApplicationModel", "Application")
                        .WithOne("DraftProgramSelection")
                        .HasForeignKey("StudentPortalPracticeTwo.Database.Models.Application.DraftStudentProgram", "ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentPortalPracticeTwo.Database.Models.Degrees.Degree", "SelectedProgram")
                        .WithMany()
                        .HasForeignKey("SelectedProgramId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StudentPortalPracticeTwo.Database.Models.Degrees.Term", "StartTerm")
                        .WithMany()
                        .HasForeignKey("StartTermId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Application");

                    b.Navigation("SelectedProgram");

                    b.Navigation("StartTerm");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Application.EmergencyContactModel", b =>
                {
                    b.HasOne("StudentPortalPracticeTwo.Database.Models.Application.ApplicationModel", "Application")
                        .WithMany("EmergencyContact")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Application.StudentContactModel", b =>
                {
                    b.HasOne("StudentPortalPracticeTwo.Database.Models.Application.ApplicationModel", "Application")
                        .WithOne("StudentContact")
                        .HasForeignKey("StudentPortalPracticeTwo.Database.Models.Application.StudentContactModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Application.StudentEssayModel", b =>
                {
                    b.HasOne("StudentPortalPracticeTwo.Database.Models.Application.ApplicationModel", "Application")
                        .WithOne("Essays")
                        .HasForeignKey("StudentPortalPracticeTwo.Database.Models.Application.StudentEssayModel", "ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Application.StudentInfoModel", b =>
                {
                    b.HasOne("StudentPortalPracticeTwo.Database.Models.Application.ApplicationModel", "Application")
                        .WithOne("StudentInfo")
                        .HasForeignKey("StudentPortalPracticeTwo.Database.Models.Application.StudentInfoModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Application.StudentProgram", b =>
                {
                    b.HasOne("StudentPortalPracticeTwo.Database.Models.Application.ApplicationModel", "Application")
                        .WithOne("StudentProgram")
                        .HasForeignKey("StudentPortalPracticeTwo.Database.Models.Application.StudentProgram", "ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentPortalPracticeTwo.Database.Models.Degrees.Degree", "SelectedProgram")
                        .WithMany()
                        .HasForeignKey("SelectedProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentPortalPracticeTwo.Database.Models.Degrees.Term", "StartTerm")
                        .WithMany()
                        .HasForeignKey("StartTermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("SelectedProgram");

                    b.Navigation("StartTerm");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Degrees.ClassSession", b =>
                {
                    b.HasOne("StudentPortalPracticeTwo.Database.Models.Degrees.Course", "Course")
                        .WithMany("Sessions")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentPortalPracticeTwo.Database.Models.Users.Faculty.Faculty", "Instructor")
                        .WithMany("ClassSessions")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentPortalPracticeTwo.Database.Models.Degrees.Term", "Term")
                        .WithMany("ClassSessions")
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Instructor");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Users.Students.UserProgramModel", b =>
                {
                    b.HasOne("StudentPortalPracticeTwo.Database.Models.Degrees.Degree", "MyDegree")
                        .WithMany("StudentPrograms")
                        .HasForeignKey("DegreeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentPortalPracticeTwo.Database.Models.Users.Students.Student", "User")
                        .WithOne("MyProgram")
                        .HasForeignKey("StudentPortalPracticeTwo.Database.Models.Users.Students.UserProgramModel", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MyDegree");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Users.UserContactModel", b =>
                {
                    b.HasOne("StudentPortalPracticeTwo.Database.Models.Users.UserModel", "User")
                        .WithOne("ContactDetails")
                        .HasForeignKey("StudentPortalPracticeTwo.Database.Models.Users.UserContactModel", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Users.UserEmergencyContactModel", b =>
                {
                    b.HasOne("StudentPortalPracticeTwo.Database.Models.Users.UserModel", "User")
                        .WithMany("EmergencyContact")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Users.UserModel", b =>
                {
                    b.HasOne("StudentPortalPracticeTwo.Database.Models.Users.ApplicationUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Users.Students.Student", b =>
                {
                    b.HasOne("StudentPortalPracticeTwo.Database.Models.Application.ApplicationModel", "OriginalFinalApplication")
                        .WithMany()
                        .HasForeignKey("FinalApplicationId");

                    b.Navigation("OriginalFinalApplication");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Application.ApplicationModel", b =>
                {
                    b.Navigation("AcademicHistory")
                        .IsRequired();

                    b.Navigation("EmergencyContact");

                    b.Navigation("Essays")
                        .IsRequired();

                    b.Navigation("StudentContact")
                        .IsRequired();

                    b.Navigation("StudentInfo")
                        .IsRequired();

                    b.Navigation("StudentProgram")
                        .IsRequired();
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Application.DraftApplicationModel", b =>
                {
                    b.Navigation("DraftAcademicHistory")
                        .IsRequired();

                    b.Navigation("DraftEmergencyContact");

                    b.Navigation("DraftEssays")
                        .IsRequired();

                    b.Navigation("DraftProgramSelection")
                        .IsRequired();

                    b.Navigation("DraftStudentContact")
                        .IsRequired();

                    b.Navigation("DraftStudentInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Degrees.Course", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Degrees.Degree", b =>
                {
                    b.Navigation("StudentPrograms");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Degrees.Term", b =>
                {
                    b.Navigation("ClassSessions");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Users.UserModel", b =>
                {
                    b.Navigation("ContactDetails")
                        .IsRequired();

                    b.Navigation("EmergencyContact");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Users.Faculty.Faculty", b =>
                {
                    b.Navigation("ClassSessions");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Users.Students.Student", b =>
                {
                    b.Navigation("MyProgram")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
