// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StudentPortalPracticeTwo.Database;

#nullable disable

namespace StudentPortalPracticeTwo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260624133457_undoauth")]
    partial class undoauth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Application.ApplicationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ApplicationDb");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Application.DraftApplicationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DraftApplicationDb");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Application.DraftStudentContactModel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DraftStudentContact");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Application.DraftStudentInfoModel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DraftStudentInfoDb");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Application.StudentContactModel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StudentContactDb");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Application.StudentInfoModel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StudentInfoDb");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Application.DraftStudentContactModel", b =>
                {
                    b.HasOne("StudentPortalPracticeTwo.Database.Models.Application.DraftApplicationModel", "Application")
                        .WithOne("DraftStudentContact")
                        .HasForeignKey("StudentPortalPracticeTwo.Database.Models.Application.DraftStudentContactModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Application.DraftStudentInfoModel", b =>
                {
                    b.HasOne("StudentPortalPracticeTwo.Database.Models.Application.DraftApplicationModel", "Application")
                        .WithOne("DraftStudentInfo")
                        .HasForeignKey("StudentPortalPracticeTwo.Database.Models.Application.DraftStudentInfoModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Application.StudentContactModel", b =>
                {
                    b.HasOne("StudentPortalPracticeTwo.Database.Models.Application.ApplicationModel", "Application")
                        .WithOne("StudentContact")
                        .HasForeignKey("StudentPortalPracticeTwo.Database.Models.Application.StudentContactModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Application.StudentInfoModel", b =>
                {
                    b.HasOne("StudentPortalPracticeTwo.Database.Models.Application.ApplicationModel", "Application")
                        .WithOne("StudentInfo")
                        .HasForeignKey("StudentPortalPracticeTwo.Database.Models.Application.StudentInfoModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Application.ApplicationModel", b =>
                {
                    b.Navigation("StudentContact")
                        .IsRequired();

                    b.Navigation("StudentInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Application.DraftApplicationModel", b =>
                {
                    b.Navigation("DraftStudentContact");

                    b.Navigation("DraftStudentInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
