// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StudentPortalPracticeTwo.Database;

#nullable disable

namespace StudentPortalPracticeTwo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CourseDegree", b =>
                {
                    b.Property<int>("CoursesId")
                        .HasColumnType("integer");

                    b.Property<int>("DegreesId")
                        .HasColumnType("integer");

                    b.HasKey("CoursesId", "DegreesId");

                    b.HasIndex("DegreesId");

                    b.ToTable("CourseDegree");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Application.ApplicationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApprovedStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ApplicationDb");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Application.DraftApplicationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DraftApplicationDb");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Application.DraftStudentContactModel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DraftStudentContact");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Application.DraftStudentInfoModel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DraftStudentInfoDb");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Application.StudentContactModel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StudentContactDb");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Application.StudentInfoModel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StudentInfoDb");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Degrees.ClassSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentCount")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Instructor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("ClassSessionDb");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Degrees.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Credits")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<int>>("DegreeId")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("CourseDb");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Degrees.Degree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("DegreeDb");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Students.UserContactModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserContactDb");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Students.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FinalApplicationId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("isDisabled")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("FinalApplicationId");

                    b.ToTable("UserDb");
                });

            modelBuilder.Entity("CourseDegree", b =>
                {
                    b.HasOne("StudentPortalPracticeTwo.Database.Models.Degrees.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentPortalPracticeTwo.Database.Models.Degrees.Degree", null)
                        .WithMany()
                        .HasForeignKey("DegreesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Application.DraftStudentContactModel", b =>
                {
                    b.HasOne("StudentPortalPracticeTwo.Database.Models.Application.DraftApplicationModel", "Application")
                        .WithOne("DraftStudentContact")
                        .HasForeignKey("StudentPortalPracticeTwo.Database.Models.Application.DraftStudentContactModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Application.DraftStudentInfoModel", b =>
                {
                    b.HasOne("StudentPortalPracticeTwo.Database.Models.Application.DraftApplicationModel", "Application")
                        .WithOne("DraftStudentInfo")
                        .HasForeignKey("StudentPortalPracticeTwo.Database.Models.Application.DraftStudentInfoModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Application.StudentContactModel", b =>
                {
                    b.HasOne("StudentPortalPracticeTwo.Database.Models.Application.ApplicationModel", "Application")
                        .WithOne("StudentContact")
                        .HasForeignKey("StudentPortalPracticeTwo.Database.Models.Application.StudentContactModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Application.StudentInfoModel", b =>
                {
                    b.HasOne("StudentPortalPracticeTwo.Database.Models.Application.ApplicationModel", "Application")
                        .WithOne("StudentInfo")
                        .HasForeignKey("StudentPortalPracticeTwo.Database.Models.Application.StudentInfoModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Degrees.ClassSession", b =>
                {
                    b.HasOne("StudentPortalPracticeTwo.Database.Models.Degrees.Course", "Course")
                        .WithMany("Sessions")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Students.UserContactModel", b =>
                {
                    b.HasOne("StudentPortalPracticeTwo.Database.Models.Students.UserModel", "User")
                        .WithOne("ContactDetails")
                        .HasForeignKey("StudentPortalPracticeTwo.Database.Models.Students.UserContactModel", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Students.UserModel", b =>
                {
                    b.HasOne("StudentPortalPracticeTwo.Database.Models.Application.ApplicationModel", "OriginalFinalApplication")
                        .WithMany()
                        .HasForeignKey("FinalApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OriginalFinalApplication");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Application.ApplicationModel", b =>
                {
                    b.Navigation("StudentContact")
                        .IsRequired();

                    b.Navigation("StudentInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Application.DraftApplicationModel", b =>
                {
                    b.Navigation("DraftStudentContact");

                    b.Navigation("DraftStudentInfo");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Degrees.Course", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("StudentPortalPracticeTwo.Database.Models.Students.UserModel", b =>
                {
                    b.Navigation("ContactDetails")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
